### ISSUE TITLE
Work Plan

### ISSUE THREAD

**Issue by gkellogg** [w3c/yaml-ld#75]
The general work plan adopted on the [August 17th](https://json-ld.org/minutes/2022-08-17/) meeting:

* [x] Define limitations on use of YAML Alias Nodes.
  * Use of aliases limited to the Extended profile.
* [x] Define more specifically the YAML-LD-JSON Profile. (PR yaml-ld#70)
* [x] Define YAML-LD-Extended Profile.
  * [x] Transparent use of %TAG for XSD and I18N namespaces (pending library support) (issue yaml-ld#17)
  * [x] Full use of YAML Alias nodes.  Not round-tripped.
* [x] Define extension points to JSON-LD API.
* [x] Test Suite (see #20)

This issue serves as a meta-issue to manage completion of different milestones.
